#!/usr/bin/env node
/* Weekly numbers digest. Answers "how are we doing" without anyone opening a
   dashboard, and gives The Verdict Drop newsletter its raw material.

   Reads only what is genuinely public through RLS — vote_counts,
   kitchen_scores, comments, articles. It deliberately does NOT call
   admin_dashboard_stats or admin_user_directory: those are owner-gated and
   would mean putting a real credential into CI, which is not worth it for a
   number you can also get by counting rows you are already allowed to read.
   So this reports activity, not the user directory. The Pulse page in the
   site remains the place for per-user data.

   Counting gotcha, learned the hard way: PostgREST caps a response at 1000
   rows, so length-of-array is not a count — the external dashboard read 1,000
   when the real number was 1,033. Every count here goes through
   Prefer: count=exact + Range: 0-0 and reads content-range instead.

   Usage: node scripts/pulse-digest.cjs                                      */
const fs = require('fs'), path = require('path');
const { ROOT, films, get, today } = require('./lib.cjs');

const SB = 'https://iherwgeuxwpapjreoofq.supabase.co/rest/v1/';
const KEY = process.env.SUPABASE_KEY || 'sb_publishable_Owy8s8-j6LzxYhDmpCo53w_7ehrsGuh';
const H = { apikey: KEY, Authorization: 'Bearer ' + KEY };

/* The only honest way to count in PostgREST. Returns null, never a guess, if
   the table or column is not readable — a missing number is reported as
   missing rather than silently rendered as zero. */
async function count(table, query) {
  /* select=* rather than a named column: `votes` has no `id` (it is keyed on
     film_slug + user_id), and asking for a column that does not exist returns
     42703 and no count header at all — which reads as "unreadable" and hides
     a real number. Range 0-0 means we still transfer exactly one row. */
  const r = await get(SB + table + '?select=*' + (query ? '&' + query : ''), Object.assign({
    Prefer: 'count=exact', Range: '0-0'
  }, H));
  const cr = r.headers['content-range'];
  if (!cr || cr.indexOf('/') < 0) return null;
  const n = parseInt(cr.split('/')[1], 10);
  return isNaN(n) ? null : n;
}

const ago = d => new Date(Date.now() - d * 86400000).toISOString();
const fmt = n => n === null ? '—' : n.toLocaleString('en-US');

(async () => {
  const week = ago(7), month = ago(30);

  const [votes, votes7, votes30, comments, comments7, arts, exc, tags] = await Promise.all([
    count('votes'), count('votes', 'created_at=gte.' + week), count('votes', 'created_at=gte.' + month),
    count('comments'), count('comments', 'created_at=gte.' + week),
    count('articles'), count('excitement_votes'), count('mini_tag_votes')
  ]);

  /* Films carrying at least one vote. vote_counts is a view, one row per
     film that has any vote at all, so its row count IS the answer — but it
     still goes through the header count, because the view can exceed 1000
     rows just as easily as a table can. */
  const scored = await get(SB + 'vote_counts?select=*', Object.assign({
    Prefer: 'count=exact', Range: '0-0'
  }, H));
  const filmsVoted = (() => {
    const cr = scored.headers['content-range'];
    return cr && cr.indexOf('/') > -1 ? parseInt(cr.split('/')[1], 10) : null;
  })();

  const catalog = films().length;
  const coverage = filmsVoted && catalog ? (filmsVoted / catalog * 100).toFixed(1) : null;

  /* Busiest films this week — real rows, capped small on purpose. */
  const recent = await get(SB + 'votes?select=film_slug&created_at=gte.' +
    week + '&limit=1000', H);
  const tally = {};
  ((recent.json) || []).forEach(v => { tally[v.film_slug] = (tally[v.film_slug] || 0) + 1; });
  const top = Object.keys(tally).sort((a, b) => tally[b] - tally[a]).slice(0, 8);
  const byId = {}; films().forEach(f => byId[f.id] = f.title);

  const L = [];
  L.push('# Pulse digest — ' + today(), '');
  L.push('_Generated by scripts/pulse-digest.cjs. Public counts only; no ' +
    'owner-gated data, no estimates. A dash means the number was not readable, ' +
    'not that it is zero._', '');

  L.push('## Verdicts', '');
  L.push('| | Count |', '| --- | ---: |');
  L.push('| Votes, all time | ' + fmt(votes) + ' |');
  L.push('| Votes, last 7 days | ' + fmt(votes7) + ' |');
  L.push('| Votes, last 30 days | ' + fmt(votes30) + ' |');
  L.push('| Films with at least one verdict | ' + fmt(filmsVoted) +
    (coverage ? ' (' + coverage + '% of ' + fmt(catalog) + ')' : '') + ' |');
  L.push('| Hype votes on unreleased titles | ' + fmt(exc) + ' |');
  L.push('| Mini-tag taps | ' + fmt(tags) + ' |', '');

  L.push('## The Table', '');
  L.push('| | Count |', '| --- | ---: |');
  L.push('| Comments, all time | ' + fmt(comments) + ' |');
  L.push('| Comments, last 7 days | ' + fmt(comments7) + ' |');
  L.push('| Published Balcony pieces | ' + fmt(arts) + ' |', '');

  L.push('## Busiest films this week', '');
  if (!top.length) {
    L.push('No votes recorded in the last 7 days.', '');
  } else {
    L.push('| Film | Verdicts |', '| --- | ---: |');
    top.forEach(id => L.push('| ' + (byId[id] || id) + ' | ' + tally[id] + ' |'));
    L.push('');
    L.push('_These are the titles worth a flyer or a Verdict Drop mention — ' +
      'the room is already there._', '');
  }

  fs.writeFileSync(path.join(ROOT, 'pulse-digest.md'), L.join('\n'));
  console.log(L.join('\n'));
})();
